#:kivy 1.8.0
#:import lg login_conn
#:import mn main

<Login>:
  name: 'login'
  BoxLayout:
    orientation: 'vertical'
    spacing: 10
    padding: [50, 50, 50, 50]

    canvas:
      Color:
        rgba: 0.5, 0.5, 0.5, 0.5
      Rectangle:
        pos: self.pos
        size: self.size   

    BoxLayout:
      spacing: 100
      size_hint_y: None

      Image:
        source: 'g934.png'

    BoxLayout:

    BoxLayout:
      size_hint_y: None
      height: 50

      Label:
        id: 'Usuario'
        text: 'Usuario'
        bold: True

      TextInput:
        id: txt_usuario
        font_size: 15
        multiline: False
        write_tab: False
        focus: True
        size_hint: [5, 0.8]
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}


    BoxLayout:
      size_hint_y: None
      height: 50

      Label:
        id: 'Senha'
        text: 'Senha'
        bold: True

      TextInput:
        id: txt_senha
        font_size: 15
        multiline: False
        write_tab: False
        password: True
        size_hint: [5, 0.8]
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}

    
    BoxLayout:
      spacing: 10
      size_hint_y: None
      
      SmoothButton:
        size_hint: .5,.45 #size hint input
        text: 'Entrar'
        font_size: 15
        size_hint: [0.3, 0.5]
        on_press: root.join_button(txt_usuario.text)
        back_color: (0.7, 0.7, 0.7, 0.5)

      SmoothButton:
        size_hint: .5,.45 #size hint input
        text: 'Cancelar'
        font_size: 15
        size_hint: [0.3, 0.5]
        on_press: root.fechar_app()
        back_color: (0.7, 0.7, 0.7, 0.5)


    BoxLayout:
      size_hint_y: None

      SmoothButton:
        size_hint: .5,.45 #size hint input
        text: 'Cadastre-se'
        font_size: 20
        back_color: (0.7, 0.7, 0.7, 0.5)
        on_press: 
          # root.ir_cadastro()
          app.root.current = 'cadastro'
          root.manager.transition.direction = 'left'
    
    BoxLayout:
      size_hint_y: None
   
      SmoothButton:
        size_hint: .5,.45 #size hint input
        text: 'Esqueci minha senha.'
        font_size: 15
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        back_color: (0.7, 0.7, 0.7, 0.5)

        on_press:
          # root.ir_alteracao()
          app.root.current = 'altera'
          root.manager.transition.direction = 'left'


<CadastroUsuarios>:
  name: 'cadastro'
  
  GridLayout:
    cols: 2
    
    Label:
      text: 'Usuario'
    TextInput:
      id: txt_cadastro_usuario
      multiline: False
      write_tab: False

    Label:
      text: 'Digite uma senha'
    TextInput:
      id: txt_cadastro_senha01
      password: True
      multiline: False
      write_tab: False

    Label:
      text: 'Confirme a senha'
    TextInput:
      id: txt_cadastro_senha02
      password: True
      multiline: False
      write_tab: False

    Button:
      id: btn_confirmar_cadastro
      text: 'Confirmar'
      on_release: root.cadastrar_usuario()

    Button:
      text: 'Cancelar'
      on_press: 
        root.voltar_login()
        root.manager.transition.direction = 'right'


<AlteraUsuarios>:
  name: 'altera'
  
  GridLayout:
    cols: 2
    
    Label:
      text: 'Usuario'
    TextInput:
      id: txt_altera_usuario
      multiline: False
      write_tab: False

    Label:
      text: 'Digite a nova senha'
    TextInput:
      id: txt_altera_senha01
      password: True
      multiline: False
      write_tab: False

    Label:
      text: 'Confirme a nova senha'
    TextInput:
      id: txt_altera_senha02
      password: True
      multiline: False

    Button:
      id: btn_confirmar_alteracao
      text: 'Confirmar'
      on_release: root.resetar_senha()
      back_color: (0.7, 0.7, 0.7, 0.5)

    Button:
      text: 'Cancelar'
      on_press: 
        root.voltar_login()
        root.manager.transition.direction = 'right'


<SmoothButton@Button>:
  background_color: (0, 0, 0, 0)
  background_normal: ''
  back_color: (1, 1, 1, 1)
  border_radius: [8]
  canvas.before:
    Color:
      rgba: self.back_color
    RoundedRectangle:
      size: self.size
      pos: self.pos
      radius: self.border_radius


<ChatLayout>:
  name: 'chat'

  BoxLayout:
    orientation: 'vertical'
    spacing: 10
    padding: [10, 10, 10, 10]

    canvas:
      Color:
        rgba: 0.5, 0.5, 0.5, 0.5
      Rectangle:
        pos: self.pos
        size: self.size
    
    BoxLayout:
      id: menubar
      size_hint: 0.5, 0.07
      spacing: 10
      SmoothButton:
        text: 'Arquivos'
        back_color: (0.7, 0.7, 0.7, 0.5)
        on_release: root.abrir()
      SmoothButton:
        text: 'Deslogar'
        back_color: (0.7, 0.7, 0.7, 0.5)
        on_release: root.logout()

    BoxLayout:
      spacing: 10

      TextInput:
        id: history
        size_hint: 0.5, 0.95 #size hint input
        multiline: True
        pos: self.pos
        size: self.size
        write_tab: False
        readonly: True

    BoxLayout:
      size_hint_y: None
      height: 50
      spacing: 10

      TextInput:
        id: nova_mensagem
        font_size: 15
        multiline: True
        write_tab: False
        focus: True
        size_hint: (2, .99)

      SmoothButton:
        size_hint: .5,.45 #size hint input
        text: 'Anexar'
        font_size: 15
        size_hint: (0.3, 0.5)
        on_release: root.show_load()
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        back_color: (0.7, 0.7, 0.7, 0.5) 
      
      SmoothButton:
        id: enviar_msg
        size_hint: .5,.45 #size hint input
        text: 'Enviar'
        font_size: 15
        size_hint: [0.3, 0.5]
        on_press: root.enviar_mensagem()
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        back_color: (0.7, 0.7, 0.7, 0.5)


<LoadDialog>:
  BoxLayout:
    size: root.size
    pos: root.pos
    orientation: "vertical"
    FileChooserListView:
      id: filechooser

    BoxLayout:
      size_hint_y: None
      height: 30
      Button:
        text: "Cancelar"
        on_release: root.cancel()

      Button:
        text: "Abrir"
        on_release: root.load(filechooser.path, filechooser.selection)


<InfoPage>:
  name: 'info'

  GridLayout:
    cols: 1

    Label:
      id: textao
      halign: 'center'
      valign: 'middle'
      font_size: 30
      text_size: self.size
